### ISSUE TITLE
[BUG] Div offset on first click for .action-button

### ISSUE THREAD

**Issue by periode** [NYUAD-IM/website#11]
It seems that when you click on one of the action buttons, like on the home page, there is a slight offset that then gets resolved on further ways to click it. Any idea how to fix it?

![screenshot from 2018-02-24 22-38-49](https://user-images.githubusercontent.com/1785254/36633721-c3fcdc7e-19b3-11e8-9367-02e1b39548c5.png)

**Comment by periode** [comment]
So the code for toggling the description is in landing.js, around lines 60-65.

My hunch is that there is a border (maybe in CSS?) that is not taken into account at the beginning, so we might need to add a white border by default?

**Comment by arantzardzm** [comment]
I found a very simple way of fixing it, I just removed the padding of .button in main.css
It also helps the offset of the action buttons in academics and opportunities. 

My solution is not responsive though. Let me know what you think.

**Comment by periode** [comment]
Thanks @arantzardzm !

I fixed the mobile friendly issue. Feel free to merge when you want!
