### ISSUE TITLE
Home page: Pop-Up blocks main menu

### ISSUE THREAD

**Issue by mjm973** [NYUAD-IM/website#18]
It one clicks on the WHAT IS IM popup and opens the top menu bar, the popup partially covers the menu. Nothing website-breaking, but kinda ugly.

**Comment by mjm973** [comment]
![impopupissue](https://user-images.githubusercontent.com/15182042/36643420-66c11212-1a64-11e8-8298-84450b082c69.PNG)

**Comment by periode** [comment]
Need to set the position of .description-left and .description-right to be a fixed pixel position that is greated than header + dropdown size

**Comment by periode** [comment]
fixed!

**Comment by mjm973** [comment]
![28461269_2008899905992432_1426531987_o](https://user-images.githubusercontent.com/15182042/36645439-5532f448-1a82-11e8-9452-ea01c0a6f2b7.png)

**Comment by mjm973** [comment]
:^)
