### ISSUE TITLE
Main: Layout Breaks on Chrome for Mobile

### ISSUE THREAD

**Issue by mjm973** [NYUAD-IM/website#30]
The layout and pop-up hiding breaks in Chrome for mobile phones. It gets fixed (sort of), however, upon tapping the WHAT CAN I DO button.

![2018-02-25 23 49 06](https://user-images.githubusercontent.com/15182042/36645759-f46956ca-1a86-11e8-892b-261201b84942.png)
![2018-02-25 23 49 12](https://user-images.githubusercontent.com/15182042/36645760-f6b16832-1a86-11e8-8139-7d4635c2f3db.png)
![2018-02-25 23 49 22](https://user-images.githubusercontent.com/15182042/36645762-f8a5055e-1a86-11e8-9b95-79da49febf3c.png)

**Comment by periode** [comment]
Fixed by adding "shrink to fit" in the viewport tag
