### ISSUE TITLE
Cannot scroll down to see the full info of people

### ISSUE THREAD

**Issue by mingwho** [NYUAD-IM/website#32]
<img width="561" alt="screen shot 2018-03-04 at 10 46 08 pm" src="https://user-images.githubusercontent.com/14964980/36949156-ee548d50-1ffd-11e8-8da2-e0ef38746e0f.png">

Cannot scroll down to see the full info of people at resolution 1280 x 530

**Comment by periode** [comment]
Thanks for catching this! Can you please post the resolution of your screen when you took that screenshot?

**Comment by periode** [comment]
fixed
