### ISSUE TITLE
loading screen for API requests?

### ISSUE THREAD

**Issue by periode** [NYUAD-IM/website#5]
Right now, it takes too much time when loading the data from the IM API in the `academics/index.html`.

We would need to add some sort of loading message while the data is being fetched -perhaps an overlay that disappears once the AJAX request in `js/fetch.js` is completed? or would it make more sense in `js/academics.js`?

**Comment by periode** [comment]
@arantzardzm I updated the load-screen branch with a white background + copied it onto every page that needed it. Feel free to open a pull request/merge it when you want!

**Comment by arantzardzm** [comment]
Can I close the issue now?

**Comment by arantzardzm** [comment]
:)

**Comment by periode** [comment]
Done with #33 

Thanks!
